from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')
pos=s.rfind('</script>')
if pos<0:
    raise SystemExit('No final script tag found')

css=r'''<style id="blaskos-inspection-tools-v1">
#recordsTools,#docsShareTools{margin-top:18px}
.tools-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}
.tools-card{border:1px solid #dbe6e2;border-radius:18px;background:#fff;padding:16px;box-shadow:0 8px 24px rgba(20,88,78,.05)}
.tools-card h3{margin:0 0 5px;font-family:Georgia,serif;color:#14584e;font-size:22px}.tools-card p{margin:0 0 12px;color:#71817d;font-size:13px;line-height:1.45}
.tools-actions{display:flex;flex-wrap:wrap;gap:8px}.tools-actions button{width:auto!important}.tools-range{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.tools-range label{font-size:11px;font-weight:700;color:#526a65}.tools-range input{margin-top:4px}
.tools-quick{display:flex;gap:7px;flex-wrap:wrap;margin:9px 0}.tools-quick button{width:auto!important;padding:8px 11px!important}.tools-status{margin-top:10px;padding:9px 11px;border-radius:10px;background:#f2f7f5;color:#526a65;font-size:12px}
.tools-checklist{display:grid;gap:7px;margin:10px 0}.tools-check{display:flex;gap:9px;align-items:center;padding:9px 10px;border:1px solid #e1e9e6;border-radius:10px;background:#fbfdfc}.tools-check input{width:auto;margin:0}
.inspection-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid #e5ece9}.inspection-row:last-child{border-bottom:0}.inspection-meta{font-size:11px;color:#71817d}.inspection-badge{font-size:10px;font-weight:800;padding:5px 8px;border-radius:999px;background:#e7f2ee;color:#14584e}.inspection-badge.expired{background:#f7e9e7;color:#9b514a}
@media(max-width:620px){.tools-grid{grid-template-columns:1fr}.tools-range{grid-template-columns:1fr}.tools-actions button{flex:1 1 140px}}
</style>'''

js=r'''<script id="blaskos-inspection-tools-v1-js">
(function(){
'use strict';
const APPKEY='blaskosPizzaAppV2';
const TOOLKEY='blaskosInspectionToolsV1';
function toolState(){try{return JSON.parse(localStorage.getItem(TOOLKEY)||'{"inspectionLinks":[],"accessLog":[]}')}catch(e){return {inspectionLinks:[],accessLog:[]}}}
function saveToolState(x){localStorage.setItem(TOOLKEY,JSON.stringify(x))}
function freshDb(){try{return JSON.parse(localStorage.getItem(APPKEY)||'{}')}catch(e){return {}}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeText(v){if(v===true)return 'Yes';if(v===false)return 'No';if(v==null||v==='')return '';return String(v)}
function fmtDateSafe(v){try{return typeof fmtDate==='function'?fmtDate(v):new Date(v+'T12:00:00').toLocaleDateString('en-GB')}catch(e){return v||''}}
function dateMinusMonths(n){const d=new Date();d.setHours(12,0,0,0);d.setMonth(d.getMonth()-n);return d.toISOString().slice(0,10)}
function getRange(){return {from:document.getElementById('toolsFrom')?.value||dateMinusMonths(3),to:document.getElementById('toolsTo')?.value||(typeof today==='function'?today():new Date().toISOString().slice(0,10))}}
function recordsInRange(db,range){return (Array.isArray(db.records)?db.records:[]).filter(r=>String(r.date||'')>=range.from&&String(r.date||'')<=range.to).sort((a,b)=>(String(a.date)+String(a.time)).localeCompare(String(b.date)+String(b.time)))}
function humanRecord(r,db){const d=r.data||{},rows=[],fridge=db.fridges?.find(x=>String(x.id)===String(d.fLocation)),supplier=db.suppliers?.find(x=>String(x.id)===String(d.fSupplier));const labels={fTemp:'Temperature (°C)',fLocation:'Location / fridge',fBy:'Signed / completed by',fNotes:'Notes',fAction:'Corrective action',fIssue:'Issue',fResolved:'Resolved',fCompleted:'Result / outcome',fFood:'Food / product',fEquipment:'Equipment',fCookTemp:'Cooking temperature (°C)',fArea:'Area / equipment',fProduct:'Cleaning product',fDeliveryDate:'Delivery date',fSupplier:'Supplier',fBatch:'Batch / lot',fCondition:'Condition',fTraceability:'Traceability',fAllergen:'Allergen check',fRejection:'Rejection',fQty:'Quantity',fLeftBottle:'Left bottle weight',fRightBottle:'Right bottle weight',leftGasPercent:'Left gas %',rightGasPercent:'Right gas %'};Object.keys(d).forEach(k=>{let v=d[k];if(k==='fLocation'&&fridge)v=fridge.name;if(k==='fSupplier'&&supplier)v=supplier.name;if(['c1','c2','c3','c4','c5','c6'].includes(k))v=v?'Checked':'Not checked';if(v!==''&&v!=null)rows.push([labels[k]||k,v])});return {type:r.type||'Record',timestamp:[r.date,r.time].filter(Boolean).join(' '),rows,signer:d.fBy||d.fRecordedBy||d.fCompletedBy||'Not specified',notes:d.fNotes||'',action:d.fAction||''}}
function csvEscape(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function recordsCsv(rs,db){const out=[['Date','Time','Record type','Field','Value','Signer','Timestamp']];rs.forEach(r=>{const h=humanRecord(r,db);if(!h.rows.length)out.push([r.date,r.time,r.type,'','',h.signer,h.timestamp]);else h.rows.forEach(x=>out.push([r.date,r.time,r.type,x[0],x[1],h.signer,h.timestamp]))});return out.map(row=>row.map(csvEscape).join(',')).join('\r\n')}
function downloadBlob(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function printHtml(title,body){const w=window.open('','_blank');if(!w){toast('Allow pop-ups to preview the report');return}w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>body{font-family:Arial,sans-serif;color:#173d38;max-width:900px;margin:30px auto;padding:0 20px}h1{font-family:Georgia,serif;color:#14584e}h2{font-size:18px;margin:25px 0 8px}.meta{color:#667a75;font-size:12px}.record{border:1px solid #d8e4df;border-radius:12px;padding:14px;margin:12px 0;break-inside:avoid}.record table{width:100%;border-collapse:collapse}.record td{padding:5px;border-bottom:1px solid #edf1ef;vertical-align:top}.record td:first-child{width:30%;font-weight:700}.sign{margin-top:10px;padding-top:9px;border-top:1px solid #d8e4df}.note{white-space:pre-wrap}@media print{body{margin:12mm}.record{break-inside:avoid}}</style></head><body>'+body+'</body></html>');w.document.close()}
function recordsReportHtml(rs,db){return '<h1>Blasko\'s Pizza — Records report</h1><p class="meta">Records only · '+esc(rs.length)+' record(s) · Generated '+esc(new Date().toLocaleString('en-GB'))+'</p>'+rs.map(r=>{const h=humanRecord(r,db);return '<section class="record"><h2>'+esc(h.type)+'</h2><div class="meta">'+esc(fmtDateSafe(r.date))+' · '+esc(r.time||'')+'</div><table>'+h.rows.map(x=>'<tr><td>'+esc(x[0])+'</td><td>'+esc(safeText(x[1]))+'</td></tr>').join('')+'</table><div class="sign"><b>Signer:</b> '+esc(h.signer)+'<br><b>Timestamp:</b> '+esc(h.timestamp)+(h.notes?'<br><b>Notes:</b> <span class="note">'+esc(h.notes)+'</span>':'')+(h.action?'<br><b>Corrective action:</b> <span class="note">'+esc(h.action)+'</span>':'')+'</div></section>'}).join('')}
function exportCsv(){const db=freshDb(),range=getRange(),rs=recordsInRange(db,range);downloadBlob('blaskos-records-'+range.from+'-to-'+range.to+'.csv',recordsCsv(rs,db),'text/csv;charset=utf-8');toast('CSV exported with '+rs.length+' record(s).')}
function exportPdf(){const db=freshDb(),rs=recordsInRange(db,getRange());printHtml('Blasko\'s Pizza — Records report',recordsReportHtml(rs,db));toast('Report preview opened. Use Print → Save as PDF.')}
function setQuick(n){document.getElementById('toolsFrom').value=dateMinusMonths(n);document.getElementById('toolsTo').value=typeof today==='function'?today():new Date().toISOString().slice(0,10);updateRangeLabel()}
function updateRangeLabel(){const el=document.getElementById('toolsRangeStatus');if(el){const r=getRange();el.textContent=recordsInRange(freshDb(),r).length+' saved record(s) in the selected range.'}}
function injectRecordsTools(){const page=document.getElementById('records');if(!page||document.getElementById('recordsTools'))return;const box=document.createElement('div');box.id='recordsTools';box.className='tools-card';box.innerHTML='<div class="eyebrow">RECORDS EXPORT</div><h3>Inspection-ready records</h3><p>Exports contain the actual saved checks, readings, results, notes, corrective actions, signer and timestamp. Supporting documents are deliberately excluded.</p><div class="tools-quick"><button class="secondary" onclick="blaskoRecordsQuick(3)">Last 3 months</button><button class="secondary" onclick="blaskoRecordsQuick(6)">Last 6 months</button><button class="secondary" onclick="blaskoRecordsQuick(12)">Last 12 months</button></div><div class="tools-range"><label>From<input id="toolsFrom" type="date" oninput="blaskoUpdateRange()"></label><label>To<input id="toolsTo" type="date" oninput="blaskoUpdateRange()"></label></div><div class="tools-actions"><button class="primary" onclick="blaskoExportRecordsPdf()">▤ Preview / save PDF</button><button class="secondary" onclick="blaskoExportRecordsCsv()">⇩ Download CSV</button></div><div class="tools-status" id="toolsRangeStatus"></div>';page.querySelector('h2')?.insertAdjacentElement('afterend',box);setQuick(3)}
function docs(){return Array.isArray(freshDb().docs)?freshDb().docs:[]}
function packHtml(db,selected,rs){return '<h1>Blasko\'s Pizza — Document pack</h1><p class="meta">Prepared '+esc(new Date().toLocaleString('en-GB'))+'</p><h2>Selected documents</h2><ul>'+selected.map(i=>docs()[i]).filter(Boolean).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>'+(rs?'<h2>Records report</h2>'+recordsReportHtml(rs,db):'<p class="meta">No records report included.</p>')+'<hr><p class="meta">Nothing is sent automatically. The pack is a previewable HTML evidence pack; attach it manually if your email client does not support file sharing.</p>'}
let currentPack=null;
function injectDocsTools(){const panel=document.getElementById('docsDocuments');if(!panel||document.getElementById('docsShareTools'))return;const box=document.createElement('div');box.id='docsShareTools';box.className='tools-card';box.innerHTML='<div class="eyebrow">SEND DOCUMENTS</div><h3>Build a share pack</h3><p>Select documents and optionally add a date-range records report. Nothing is sent automatically.</p><div id="packDocs" class="tools-checklist"></div><label><input id="packIncludeRecords" type="checkbox" onchange="blaskoTogglePackRange()"> Include records report</label><div id="packRange" style="display:none"><div class="tools-range"><label>From<input id="packFrom" type="date"></label><label>To<input id="packTo" type="date"></label></div><div class="tools-quick"><button class="secondary" onclick="blaskoPackQuick(3)">3 months</button><button class="secondary" onclick="blaskoPackQuick(6)">6 months</button><button class="secondary" onclick="blaskoPackQuick(12)">12 months</button></div></div><div class="tools-actions"><button class="primary" onclick="blaskoBuildPack()">Create previewable pack</button><button class="secondary" onclick="blaskoSharePack()">Share pack</button><button class="secondary" onclick="blaskoEmailPack()">Open email composer</button></div><div class="tools-status" id="packStatus">No pack created yet.</div>';panel.appendChild(box);renderPackDocs();blaskoPackQuick(3)}
function renderPackDocs(){const el=document.getElementById('packDocs');if(!el)return;el.innerHTML=docs().length?docs().map((d,i)=>'<label class="tools-check"><input type="checkbox" data-pack-doc="'+i+'" checked> <span>'+esc(d)+'</span></label>').join(''):'<div class="tools-status">No document names have been added yet.</div>'}
function packRange(){return {from:document.getElementById('packFrom')?.value||dateMinusMonths(3),to:document.getElementById('packTo')?.value||(typeof today==='function'?today():new Date().toISOString().slice(0,10))}}
function blaskoPackQuick(n){const a=document.getElementById('packFrom'),b=document.getElementById('packTo');if(a)a.value=dateMinusMonths(n);if(b)b.value=typeof today==='function'?today():new Date().toISOString().slice(0,10)}
function blaskoTogglePackRange(){const e=document.getElementById('packIncludeRecords');document.getElementById('packRange').style.display=e?.checked?'block':'none'}
function selectedPackDocs(){return [...document.querySelectorAll('[data-pack-doc]')].filter(x=>x.checked).map(x=>Number(x.dataset.packDoc))}
function blaskoBuildPack(){const db=freshDb(),selected=selectedPackDocs(),include=document.getElementById('packIncludeRecords').checked,r=packRange(),rs=include?recordsInRange(db,r):null;currentPack={html:'<!doctype html><html><head><meta charset="utf-8"><title>Blasko\'s Pizza document pack</title></head><body>'+packHtml(db,selected,rs)+'</body></html>',selected,include,r};currentPack.file=new File([new Blob([currentPack.html],{type:'text/html'})],'blaskos-document-pack.html',{type:'text/html'});const w=window.open('','_blank');if(w){w.document.write(currentPack.html);w.document.close()}document.getElementById('packStatus').textContent='Pack ready: '+selected.length+' document(s)'+(include?' + '+rs.length+' record(s)':'')+'.'}
function blaskoSharePack(){if(!currentPack){blaskoBuildPack();setTimeout(blaskoSharePack,300);return}if(navigator.share&&navigator.canShare?.({files:[currentPack.file]})){navigator.share({title:'Blasko\'s Pizza document pack',text:'Blasko\'s Pizza compliance document pack',files:[currentPack.file]}).catch(()=>{})}else{downloadBlob('blaskos-document-pack.html',currentPack.html,'text/html');toast('Pack downloaded. Use the phone share sheet to send it.')}}
function blaskoEmailPack(){if(!currentPack)blaskoBuildPack();downloadBlob('blaskos-document-pack.html',currentPack.html,'text/html');setTimeout(()=>{location.href='mailto:?subject='+encodeURIComponent("Blasko's Pizza compliance document pack")+'&body='+encodeURIComponent('The pack has been downloaded. Attach blaskos-document-pack.html before sending.')},350)}
function scrubPrivate(v){if(Array.isArray(v))return v.map(scrubPrivate);if(v&&typeof v==='object'){const o={};Object.entries(v).forEach(([k,x])=>{if(/phone|mobile|email|contact|password|token|secret|session/i.test(k))return;o[k]=scrubPrivate(x)});return o}return v}
function publicInspectionData(db){return {businessName:db.settings?.businessName||"Blasko's Pizza",records:(db.records||[]).map(r=>{const h=humanRecord(r,db);return {type:h.type,date:r.date,time:r.time,rows:h.rows,signer:h.signer,timestamp:h.timestamp,notes:h.notes,action:h.action}}),reviews:scrubPrivate(db.managerReviews||db.reviews||[]),probeEvidence:scrubPrivate(db.probeChecks||db.probeEvidence||[]),documents:db.docs||[],premises:(db.premises||[]).map(p=>({name:p.name,address:p.address,notes:p.notes})),photos:[]}}
function inspectionSnapshotHtml(payload,token){return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EHO view — '+esc(payload.businessName)+'</title><style>body{font-family:Arial,sans-serif;background:#f8f0e3;color:#173d38;margin:0}.head{background:#14584e;color:white;padding:28px 20px}.wrap{max-width:980px;margin:auto;padding:20px}.card{background:#fff;border:1px solid #d9e4df;border-radius:16px;padding:16px;margin:14px 0}.record{border-top:1px solid #e2e9e6;padding:12px 0}.record:first-child{border-top:0}.muted{color:#71817d;font-size:12px}.photo{max-width:100%;border-radius:10px}h1,h2{font-family:Georgia,serif}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head><body><header class="head"><div class="wrap"><div style="font-size:11px;letter-spacing:2px">READ-ONLY EHO VIEW</div><h1>'+esc(payload.businessName)+'</h1><div style="color:#d8ebe5">No editing, uploads or staff details are available.</div></div></header><main class="wrap"><div class="card"><b>Access</b><div class="muted">This inspection snapshot expires '+esc(new Date(token.expiresAt).toLocaleString('en-GB'))+'.</div></div><div class="card"><h2>Records</h2>'+payload.records.map(r=>'<div class="record"><b>'+esc(r.type)+'</b><div class="muted">'+esc(fmtDateSafe(r.date))+' · '+esc(r.time||'')+'</div>'+r.rows.map(x=>'<div><b>'+esc(x[0])+':</b> '+esc(x[1])+'</div>').join('')+'<div class="muted">Signer: '+esc(r.signer)+' · Timestamp: '+esc(r.timestamp)+'</div>'+(r.notes?'<div><b>Notes:</b> '+esc(r.notes)+'</div>':'')+(r.action?'<div><b>Corrective action:</b> '+esc(r.action)+'</div>':'')+'</div>').join('')+'</div><div class="card"><h2>Manager reviews</h2><pre style="white-space:pre-wrap">'+esc(JSON.stringify(payload.reviews,null,2))+'</pre></div><div class="card"><h2>Probe evidence</h2><pre style="white-space:pre-wrap">'+esc(JSON.stringify(payload.probeEvidence,null,2))+'</pre></div><div class="card"><h2>Documents</h2><ul>'+payload.documents.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div><div class="card"><h2>Premises</h2>'+payload.premises.map(p=>'<div><b>'+esc(p.name)+'</b><div>'+esc(p.address||'')+'</div><div>'+esc(p.notes||'')+'</div></div>').join('')+'</div><div class="card"><h2>Premises photos</h2>'+payload.photos.map(x=>'<figure><img class="photo" src="'+x.dataUrl+'" alt="'+esc(x.note||'Premises photo')+'"><figcaption class="muted">'+esc(fmtDateSafe(x.date))+' · '+esc(x.note||'Premises photo')+'</figcaption></figure>').join('')+'</div></main></body></html>'}
async function ownerVerify(){const pin=prompt('Owner verification: enter your owner PIN.');if(pin===null)return false;if(pin.length<4){toast('PIN must be at least 4 characters.');return false}const hashBuf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(pin)),hash=[...new Uint8Array(hashBuf)].map(x=>x.toString(16).padStart(2,'0')).join(''),st=toolState();if(!st.ownerPinHash){st.ownerPinHash=hash;saveToolState(st);toast('Owner PIN set for this browser.');return true}if(st.ownerPinHash!==hash){toast('Incorrect owner PIN.');return false}return true}
async function backupPhotos(){const out=[];if(typeof getPremiseImage!=='function')return out;for(const p of (freshDb().premisePhotos||[])){try{const image=await getPremiseImage(String(p.id));if(image)out.push({id:String(p.id),date:p.date,note:p.note,premiseId:p.premiseId,dataUrl:image})}catch(e){}}return out}
async function createInspection(){const db=freshDb();if(!(await ownerVerify()))return;const state=toolState(),token={id:crypto.randomUUID(),createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+24*60*60*1000).toISOString(),revoked:false},payload=publicInspectionData(db);payload.photos=await backupPhotos();const html=inspectionSnapshotHtml(payload,token),encoded=btoa(unescape(encodeURIComponent(JSON.stringify({token,payload,html}))));const url=location.origin+location.pathname+'#eho='+encodeURIComponent(encoded);state.inspectionLinks.unshift({id:token.id,createdAt:token.createdAt,expiresAt:token.expiresAt,revoked:false,url,openedAt:null});state.accessLog.unshift({event:'created',id:token.id,at:token.createdAt});saveToolState(state);renderInspectionLinks();if(navigator.share)navigator.share({title:'Blasko\'s Pizza EHO inspection view',text:'Read-only inspection view. Expires in 24 hours.',url}).catch(()=>{});else{navigator.clipboard?.writeText(url);toast('Inspection link created and copied if your browser allowed it.')}}
function renderInspectionLinks(){const el=document.getElementById('inspectionLinks');if(!el)return;const st=toolState();el.innerHTML=st.inspectionLinks.length?st.inspectionLinks.slice(0,8).map(x=>{const expired=Date.now()>Date.parse(x.expiresAt);return '<div class="inspection-row"><div><b>'+esc(new Date(x.createdAt).toLocaleString('en-GB'))+'</b><div class="inspection-meta">Expires '+esc(new Date(x.expiresAt).toLocaleString('en-GB'))+'</div></div><span class="inspection-badge '+(x.revoked||expired?'expired':'')+'">'+(x.revoked?'Revoked':expired?'Expired':'Active')+'</span><button class="secondary" onclick="blaskoRevokeInspection(\''+x.id+'\')">Revoke</button></div>'}).join(''):'<div class="tools-status">No inspection links created.</div>'}
function revokeInspection(id){const st=toolState(),x=st.inspectionLinks.find(a=>a.id===id);if(!x)return;x.revoked=true;st.accessLog.unshift({event:'revoked',id,at:new Date().toISOString()});saveToolState(st);renderInspectionLinks();toast('Inspection link revoked in this owner app.')}
function injectInspectionTools(){const panel=document.getElementById('docsDocuments');if(!panel||document.getElementById('inspectionTools'))return;const box=document.createElement('div');box.id='inspectionTools';box.className='tools-card';box.innerHTML='<div class="eyebrow">READ-ONLY EHO VIEW</div><h3>Inspection access</h3><p>Create a time-limited inspection snapshot. It contains records, manager reviews, probe evidence, documents and captioned premises photos, but no staff list or editing controls.</p><div class="tools-actions"><button class="primary" onclick="blaskoCreateInspection()">Create 24-hour view</button></div><div id="inspectionLinks" style="margin-top:8px"></div><div class="tools-status">This static app creates a portable, time-limited snapshot. True cross-device revocation and owner-side open-event logging require a server-backed inspection service; a copied snapshot cannot be recalled from another device.</div>';panel.appendChild(box);renderInspectionLinks()}
function backupJson(db){const copy=JSON.parse(JSON.stringify(db));['password','passwordHash','session','sessionToken','accessToken','refreshToken','tokens'].forEach(k=>delete copy[k]);return JSON.stringify(copy,null,2)}
function csvSimple(obj){const rows=[['Key','Value']];Object.entries(obj||{}).forEach(([k,v])=>rows.push([k,typeof v==='object'?JSON.stringify(v):v]));return rows.map(r=>r.map(csvEscape).join(',')).join('\r\n')}
function dataUrlBytes(dataUrl){const b64=String(dataUrl||'').split(',')[1]||'',bin=atob(b64),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function tarHeader(name,size,mode=0o644){const h=new Uint8Array(512),e=new TextEncoder(),put=(off,len,val)=>{h.set(e.encode(String(val)).slice(0,len),off)},oct=(off,len,val)=>put(off,len,Number(val).toString(8).padStart(len-1,'0')+'\0');put(0,100,name);oct(100,8,mode);oct(108,8,0);oct(116,8,0);oct(124,12,size);oct(136,12,Math.floor(Date.now()/1000));for(let i=148;i<156;i++)h[i]=32;put(156,1,'0');put(257,6,'ustar');put(263,2,'00');let sum=0;for(const x of h)sum+=x;oct(148,8,sum);return h}
function makeTar(files){const chunks=[];for(const f of files){const data=typeof f.content==='string'?new TextEncoder().encode(f.content):f.content;chunks.push(tarHeader(f.name,data.length));chunks.push(data);const pad=(512-data.length%512)%512;if(pad)chunks.push(new Uint8Array(pad))}chunks.push(new Uint8Array(1024));const total=chunks.reduce((n,x)=>n+x.length,0),out=new Uint8Array(total);let o=0;chunks.forEach(x=>{out.set(x,o);o+=x.length});return out}
async function makeBackup(){if(!(await ownerVerify()))return;const db=freshDb(),before=JSON.stringify(db),photos=await backupPhotos(),manifest={format:'Blasko\'s Pizza backup v1',createdAt:new Date().toISOString(),records:db.records?.length||0,documents:db.docs?.length||0,premisesPhotos:photos.length,files:['manifest.json','data.json','records.csv','configuration.csv','evidence.json',...photos.map(x=>'premises-photos/'+x.id+'.jpg')],note:'Independent evidence copy. Unless a tested restore function exists, restoring this backup may require technical work.'},files=[{name:'manifest.json',content:JSON.stringify(manifest,null,2)},{name:'data.json',content:backupJson(db)},{name:'records.csv',content:recordsCsv(db.records||[],db)},{name:'configuration.csv',content:csvSimple({settings:db.settings,fridges:db.fridges,suppliers:db.suppliers,docs:db.docs,premises:db.premises})},{name:'evidence.json',content:JSON.stringify({allergenPizzas:db.allergenPizzas||[],managerReviews:db.managerReviews||db.reviews||[],probeEvidence:db.probeChecks||db.probeEvidence||[],premisePhotos:db.premisePhotos||[]},null,2)}];photos.forEach(x=>files.push({name:'premises-photos/'+x.id+'.jpg',content:dataUrlBytes(x.dataUrl)}));downloadBlob('blaskos-backup-'+new Date().toISOString().slice(0,10)+'.tar',makeTar(files),'application/x-tar');toast('Complete backup created. Production data '+(before===JSON.stringify(freshDb())?'was not changed.':'changed unexpectedly — investigate before relying on this backup.'))}
function injectBackupTools(){const panel=document.getElementById('docsDocuments');if(!panel||document.getElementById('backupTools'))return;const box=document.createElement('div');box.id='backupTools';box.className='tools-card';box.innerHTML='<div class="eyebrow">BACKUP</div><h3>Complete owner backup</h3><p>Downloads JSON/CSV data, configuration, stored premises photo evidence, controlled built-in evidence and a manifest. Passwords, session secrets and access tokens are excluded.</p><div class="tools-actions"><button class="primary" onclick="blaskoCreateBackup()">⇩ Create complete backup</button><button class="secondary" onclick="blaskoRunToolTests()">Run non-destructive self-test</button></div><div class="tools-status">Backup is independent evidence. Unless a tested restore function exists, restoring it may require technical work.</div><div id="toolTestStatus" class="tools-status" style="display:none"></div>';panel.appendChild(box)}
function selfTest(){const db=freshDb(),before=JSON.stringify(db),sample={id:'test',type:'Temperature check',date:typeof today==='function'?today():new Date().toISOString().slice(0,10),time:'12:34',data:{fTemp:'4.2',fLocation:'test-fridge',fBy:'Test signer',fNotes:'Test note',fAction:'Test action'}},h=humanRecord(sample,db),csv=recordsCsv([sample],db),pass1=csv.includes('4.2')&&csv.includes('Test signer')&&csv.includes('Test action'),pass2=h.rows.some(x=>x[0]==='Temperature (°C)'),filtered=publicInspectionData({...db,records:[sample],staff:[{name:'PRIVATE'}]}),pass3=!JSON.stringify(filtered).includes('PRIVATE'),st=toolState(),id='selftest-'+Date.now();st.inspectionLinks.push({id,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+1000).toISOString(),revoked:false,url:'',openedAt:null});saveToolState(st);revokeInspection(id);const pass4=toolState().inspectionLinks.find(x=>x.id===id)?.revoked===true,pass5=before===JSON.stringify(freshDb());return {csv:pass1?'PASS':'FAIL',details:pass2?'PASS':'FAIL',ehoStaffIsolation:pass3?'PASS':'FAIL',revocation:pass4?'PASS':'FAIL',productionUnchanged:pass5?'PASS':'FAIL'}}
function runToolTests(){const r=selfTest(),el=document.getElementById('toolTestStatus');if(el){el.style.display='block';el.innerHTML='<b>Non-destructive self-test</b><br>'+Object.entries(r).map(([k,v])=>esc(k)+': <b>'+esc(v)+'</b>').join('<br>')+'<br><span class="muted">PDF/pack rendering is exercised by their preview functions; browser print/share support depends on the device.</span>'}toast('Self-test complete. No production records were deleted.')}
function handleInspectionHash(){const h=location.hash||'';if(!h.startsWith('#eho='))return;try{const raw=decodeURIComponent(h.slice(5)),data=JSON.parse(decodeURIComponent(escape(atob(raw))));if(!data.token||Date.now()>Date.parse(data.token.expiresAt)){document.body.innerHTML='<main style="font-family:Arial;padding:30px"><h1>Inspection link expired</h1><p>This read-only inspection view is no longer available.</p></main>';return}document.body.innerHTML=data.html.replace('</body>','<div style="position:fixed;bottom:10px;right:10px;background:#14584e;color:#fff;padding:7px 10px;border-radius:8px;font:11px Arial">Opened '+new Date().toLocaleString('en-GB')+'</div></body>');localStorage.setItem('blaskosInspectionOpened:'+data.token.id,new Date().toISOString())}catch(e){document.body.innerHTML='<main style="font-family:Arial;padding:30px"><h1>Invalid inspection link</h1><p>The inspection view could not be opened.</p></main>'}}
window.blaskoRecordsQuick=setQuick;window.blaskoUpdateRange=updateRangeLabel;window.blaskoExportRecordsPdf=exportPdf;window.blaskoExportRecordsCsv=exportCsv;window.blaskoPackQuick=blaskoPackQuick;window.blaskoTogglePackRange=blaskoTogglePackRange;window.blaskoBuildPack=blaskoBuildPack;window.blaskoSharePack=blaskoSharePack;window.blaskoEmailPack=blaskoEmailPack;window.blaskoCreateInspection=createInspection;window.blaskoRevokeInspection=revokeInspection;window.blaskoCreateBackup=makeBackup;window.blaskoRunToolTests=runToolTests;
function boot(){if(location.hash.startsWith('#eho=')){handleInspectionHash();return}injectRecordsTools();injectDocsTools();injectInspectionTools();injectBackupTools();updateRangeLabel()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.addEventListener('load',boot);
})();
</script>'''
insert_at=pos+len('</script>')
s=s[:insert_at]+'\n'+css+'\n'+js+s[insert_at:]
p.write_text(s,encoding='utf-8')
